import { FixedClock } from '../../../../shared/application/clock/fixed-clock';
import { ConflictError } from '../../../../shared/application/errors/application.error';
import { IdGenerator } from '../../../../shared/application/ids/id-generator';
import { User } from '../../../users/domain/entities/user.entity';
import { UserRole } from '../../../users/domain/enums/user-role.enum';
import { UsersRepository } from '../../../users/domain/repositories/users.repository';
import { PasswordHasher } from '../contracts/password-hasher';
import { RegisterUserUseCase } from './register-user.use-case';

const now = new Date('2026-06-29T12:00:00.000Z');

function makeUsersRepository(existingUser: User | null = null): UsersRepository {
  return {
    create: jest.fn().mockImplementation(async (user: User) => user),
    findMany: jest.fn(),
    findById: jest.fn(),
    findByEmail: jest.fn().mockResolvedValue(existingUser),
    findByEmailIncludingDeleted: jest.fn().mockResolvedValue(existingUser),
  };
}

function makePasswordHasher(): PasswordHasher {
  return {
    hash: jest.fn().mockResolvedValue('argon2id-hash'),
    verify: jest.fn(),
  };
}

function makeIdGenerator(): IdGenerator {
  return {
    generate: jest.fn().mockReturnValue('356b57c6-9b8a-4576-8df6-cbd9799d8295'),
  };
}

describe('RegisterUserUseCase', () => {
  it('registers a user with Argon2id hash generated by abstraction', async () => {
    const usersRepository = makeUsersRepository();
    const passwordHasher = makePasswordHasher();
    const useCase = new RegisterUserUseCase(
      usersRepository,
      passwordHasher,
      makeIdGenerator(),
      new FixedClock(now),
    );

    await expect(
      useCase.execute({
        name: 'HIT User',
        email: 'USER@hit.local',
        password: 'User123!',
      }),
    ).resolves.toEqual({
      id: '356b57c6-9b8a-4576-8df6-cbd9799d8295',
      name: 'HIT User',
      email: 'user@hit.local',
      role: UserRole.USER,
      createdAt: '2026-06-29T12:00:00.000Z',
      updatedAt: '2026-06-29T12:00:00.000Z',
    });
    expect(usersRepository.findByEmailIncludingDeleted).toHaveBeenCalledWith('user@hit.local');
    expect(passwordHasher.hash).toHaveBeenCalledWith('User123!');
    expect(usersRepository.create).toHaveBeenCalledWith(expect.any(User));
  });

  it('throws ConflictError when email is already in use by an active user', async () => {
    const existingUser = User.create({
      id: 'b4b73ab8-a610-4b33-b9e4-c79d3f94ed45',
      name: 'Existing User',
      email: 'user@hit.local',
      passwordHash: 'argon2id-hash',
      role: UserRole.USER,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    });
    const useCase = new RegisterUserUseCase(
      makeUsersRepository(existingUser),
      makePasswordHasher(),
      makeIdGenerator(),
      new FixedClock(now),
    );

    await expect(
      useCase.execute({
        name: 'HIT User',
        email: 'user@hit.local',
        password: 'User123!',
      }),
    ).rejects.toThrow(ConflictError);
  });

  it('throws ConflictError when email belongs to a soft-deleted user', async () => {
    const deletedUser = User.create({
      id: 'b4b73ab8-a610-4b33-b9e4-c79d3f94ed45',
      name: 'Deleted User',
      email: 'user@hit.local',
      passwordHash: 'argon2id-hash',
      role: UserRole.USER,
      createdAt: now,
      updatedAt: now,
      deletedAt: new Date('2026-06-29T13:00:00.000Z'),
    });
    const useCase = new RegisterUserUseCase(
      makeUsersRepository(deletedUser),
      makePasswordHasher(),
      makeIdGenerator(),
      new FixedClock(now),
    );

    await expect(
      useCase.execute({
        name: 'HIT User',
        email: 'user@hit.local',
        password: 'User123!',
      }),
    ).rejects.toThrow(ConflictError);
  });
});
