export const LOGGER_REDACTION_PATHS = [
  'req.headers.authorization',
  'req.headers.cookie',
  'res.headers["set-cookie"]',
  'req.body.password',
  'req.body.passwordHash',
  'req.body.accessToken',
  'req.body.token',
  'req.body.jwt',
  'req.body.secret',
  'body.password',
  'body.passwordHash',
  'body.accessToken',
  'body.token',
  'body.jwt',
  'body.secret',
  'user.password',
  'user.passwordHash',
  'authorization',
  'cookie',
  'password',
  'passwordHash',
  'accessToken',
  'token',
  'jwt',
  'secret',
  'DATABASE_URL',
  'JWT_SECRET',
] as const;

export const LOGGER_REDACTION_CENSOR = '[REDACTED]';
